### ISSUE TITLE
P2 seems not correct

### ISSUE THREAD

**Issue by ursinedeity** [saketkc/hatex#1]
The homework question doesn't seem to be the same as the problem discussed in class. It's "pdf of radius of the first drop to cover the orgin"

**Comment by saketkc** [comment]
True. I didn't really get close to solve it.
However, the solution lies in considering the joint probability for $\tau < t$ and $R <r$. I was not able to reduce it to what it should actually be. My solution is wrong and was just an attempt in a possibly correct direction.

**Comment by saketkc** [comment]
Thanks for checking though!

**Comment by saketkc** [comment]
was almost correct.
